// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEQ9KS1Sq6CYhNa6FMeBoU9GEZ2ulqwPA',
    appId: '1:951483203031:web:003f03573020511796df92',
    messagingSenderId: '951483203031',
    projectId: 'nihongona-fd36e',
    authDomain: 'nihongona-fd36e.firebaseapp.com',
    storageBucket: 'nihongona-fd36e.firebasestorage.app',
    measurementId: 'G-JXWVQ3BPMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF6xYoZ6jQ2jLPSa3ZfAGisSkmwgyPe88',
    appId: '1:951483203031:android:e25ca0a4a37584cb96df92',
    messagingSenderId: '951483203031',
    projectId: 'nihongona-fd36e',
    storageBucket: 'nihongona-fd36e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACL6RY0VO0pH2FWyAdzM13Mk_xfgFSIvY',
    appId: '1:951483203031:ios:d1c9f2a1e48c925896df92',
    messagingSenderId: '951483203031',
    projectId: 'nihongona-fd36e',
    storageBucket: 'nihongona-fd36e.firebasestorage.app',
    iosBundleId: 'com.bon.nihongona',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACL6RY0VO0pH2FWyAdzM13Mk_xfgFSIvY',
    appId: '1:951483203031:ios:8a00b2f52bfba06e96df92',
    messagingSenderId: '951483203031',
    projectId: 'nihongona-fd36e',
    storageBucket: 'nihongona-fd36e.firebasestorage.app',
    iosBundleId: 'com.example.wakeNihongo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEQ9KS1Sq6CYhNa6FMeBoU9GEZ2ulqwPA',
    appId: '1:951483203031:web:7f81d42b52730ef596df92',
    messagingSenderId: '951483203031',
    projectId: 'nihongona-fd36e',
    authDomain: 'nihongona-fd36e.firebaseapp.com',
    storageBucket: 'nihongona-fd36e.firebasestorage.app',
    measurementId: 'G-1HYNJ5842J',
  );
}
